# Generated by Django 4.0.3 on 2022-03-27 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='imgae',
            new_name='image',
        ),
    ]
