# Generated by Django 4.0.3 on 2022-03-12 15:34

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_job_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='published_ad',
            new_name='published_at',
        ),
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(upload_to=job.models.image_upload),
        ),
    ]
