# Generated by Django 4.0.3 on 2022-03-12 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_rename_published_ad_job_published_at_alter_job_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Vacancy',
            new_name='vacancy',
        ),
    ]
