# Generated by Django 4.0.3 on 2022-03-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_alter_apply_coverletter_alter_apply_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
