# Generated by Django 4.0.3 on 2022-03-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_apply_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='apply/'),
        ),
    ]
