# Generated by Django 4.0.3 on 2022-03-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_alter_apply_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='cv',
            field=models.FileField(default='', upload_to='apply/'),
            preserve_default=False,
        ),
    ]
