# Generated by Django 4.0.3 on 2022-03-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0019_alter_job_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='same_slugs',
            field=models.IntegerField(default=0),
        ),
    ]
